### ISSUE TITLE
[Feat] FastAPI 환경 구축

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-Code-Analysis-Server#1]
## 📝 Description
**무엇을?**
- FastAPI 환경 구축과 구조 설정

## ❗️Todo
- [x] 설치
- [x] 패키지 구조 찾아보기
- [x] 생성

## ETC
기타사항

**Comment by ujkkk** [comment]
![image](https://github.com/Co-due/Code-Analysis-Server/assets/88374384/f68789fd-c172-4cd4-bbd6-29049f6a5f82)
모든 도메인 디렉토리의 root는 app이다

main.py에서는 그대로 FastAPI app을 초기화하고 프로젝트의 root 역할을 한다 (보편적으로 src/ 느낌)
controller : 각 모듈의 엔드포인트를 가진다
enums : Enum 모델들
models : pydantic 모델들
entities : 엔티티 모델들
service : 모듈 별 비즈니스 로직 담당
dependencies : 유효성 검사
constant : 모듈 내에서 사용되는 상수값
config : 모듈 내의 설정사항
exceptions: 커스텀 예외들!
같은 관심을 갖는 메서드가 두개 이상일 경우 따로 패키지로 분류한다

외부 패키지의 경우 app에 종속적이지 않기 때문에 app 외부에서 관리한다.

https://taptorestart.tistory.com/entry/FastAPI-%EB%94%94%EB%A0%89%ED%84%B0%EB%A6%AC-%EA%B5%AC%EC%A1%B0%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%98%EB%8A%94-%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C

**Comment by SongGwanSeok** [comment]
**생성**

![스크린샷 2024-06-04 오후 3 21 05](https://github.com/Co-due/Code-Analysis-Server/assets/105411445/ff0fee46-3357-4553-8513-4891f2e9753f)
