### ISSUE TITLE
[Feat] 리스트 자료구조 분석 후 json 구조 정의

### ISSUE THREAD

**Issue by ujkkk** [edu-pi/Backend-Code-Analysis-Server#38]
## 📝 Description
**무엇을?**
- 리스트 자료구조 분석 후 JSON 정의

**왜?**
- 리스트 자료구조 시각화 추가

## ❗️Todo
- [x] 분석 후 기존 JSON구조와 합쳐서 JSON 구조 작성
- [ ] 
- [ ]

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
[assign과 list json 자료구조](https://www.notion.so/front-json-a4ad9a98ba3348cdb8eb9fde623d2bfb)

list가 추가되고 시각화 할 때 코드 흐름 부분에서 값을 만들어 변수에 할당하도록 그림이 바뀌었기 때문에 json구조도 변경되었다.
