### ISSUE TITLE
[Refactor] parser와 generator 클래스들을 static으로 전환

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#66]
## 📝 Description
**무엇을?**
- BinopParser, ConstantParser, NameParser, TupleParser, AssignGenerator 클래스들을 static화

**왜?**
- 인스턴스를 만들어서 사용할 필요가 없다고 판단

## ❗️Todo
- [x] BinopParser
- [x] ConstantParser
- [x] NameParser
- [x] TupleParser
- [x] AssignGenerator

## ETC
기타사항

**Comment by ujkkk** [comment]
**장점**
인스턴스 생성 비용을 줄인다
함수를 호출하는데 편하다


**단점**
모든 함수가 static이 되어서 충돌 발생 가능성이 있을 것 같다
인스턴스 관리가 어렵다
연관된 모든 함수를 static으로 만들어야 한다. => 기능이 많아질수록 추적하기 어려워짐

**결론**
parse는 static으로 parse에 필요한 메소드들은 instance로 생성하자

**이유**
- parse를 static으로 선언해서 함수사용이 간결해지고 편해짐. 유일한 진입점이기 때문에 사용에 유용
- 정적 메소드에서 인스턴스 메소드를 호출함으로써 인스턴스 상태 활용 가능 -> 복잡한 로직 처리 유용
- 한 클래스 내에서 여러 함수를 호출함 -> 변수관리를 하지 않는 static의 유용성과는 맞지 않다고 생각함.
