### ISSUE TITLE
[Docs] decoupling 작업 이후 파일과 클래스 구조 위키 제작

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#96]
## 📝 Description
**무엇을?**
- (ex 사용자 인증 기능)

**왜?**
- (ex 사용자를 인증하기 위해)

## ❗️Todo
- [ ] 
- [ ] 
- [ ]

## ETC
기타사항

**Comment by ujkkk** [comment]
https://yielding-radio-61a.notion.site/c2e05b82ef554fb08baee19d3be7efb9?pvs=4

**Comment by SongGwanSeok** [comment]
[expr obj 정리](https://www.notion.so/Expr-Parser-Object-8fda885622184062ab505e132757a9be)
